# Site settings
title: Bryce Stradling - He is goddamn amazing
email: brycestradling@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bryce Stradling - Creative
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brycestradling.com" # the base hostname & protocol for your site
twitter_username: losslessdesign
github_username:  Cutcopy

#Handling Reading
encoding: "utf-8"
markdown_ext: "markdown, md"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems:
  - jemoji

# Excludes
exclude:
  - node_modules

sass:
  sass_dir: _sass
  style: :nested
